switch(argument[0]) {
    case 0:
        return $0;
    case 1:
        return $1;
    case 2:
        return $2;
    case 3:
        return $4;
    case 4:
        return $8;
    case 5:
        return $10;
    case 6:
        return $20;
    case 7:
        return $40;
    case 8:
        return $80;
    case 9:
        return $100;
    case 10:
        return $200;
    case 11:
        return $400;
    case 12:
        return $800;
}
