switch(argument[0]) {
    case 0:
        return $fffffff;
    case 1:
        return $ffffffe;
    case 2:
        return $ffffffd;
    case 3:
        return $ffffffb;
    case 4:
        return $ffffff7;
    case 5:
        return $fffffef;
    case 6:
        return $fffffdf;
    case 7:
        return $fffffbf;
    case 8:
        return $fffff7f;
    case 9:
        return $ffffeff;
    case 10:
        return $ffffdff;
    case 11:
        return $ffffbff;
    case 12:
        return $ffff7ff;
    case 13:
        return $fffefff;
    case 14:
        return $fffdfff;
    case 15:
        return $fffbfff;
    case 16:
        return $fff7fff;
    case 17:
        return $ffeffff;
    case 18:
        return $ffdffff;
    case 19:
        return $ffbffff;
    case 20:
        return $ff7ffff;
    case 21:
        return $fefffff;
    case 22:
        return $fdfffff;
    case 23:
        return $fbfffff;
    case 24:
        return $f7fffff;
    case 25:
        return $effffff;
    case 26:
        return $dffffff;
    case 27:
        return $bffffff;
    case 28:
        return $7ffffff;
    default:
        show_error("Bitoption out of range", false);
}
return $0;
